[package]
name = "buildwright"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "buildwright"
path = "src/main.rs"

[dependencies]
data_miner = { path = "../data_miner" }
json = { path = "../json" }
hash = { path = "../hash" }

[lints]
workspace = true
